"""Validated scientific and execution specifications.

See :mod:`dynamisbench.domain` for the owned definitions and their separation
requirements (ADR-002). DB-1.2 (RES-228) introduces the Pydantic v2 domain model:
the validated semantic representation. YAML and JSON are authoring
representations only, and no engine-native type is reachable from this package
(ADR-001).
"""

from dynamisbench.domain.spec.base import (
    DomainModel,
    NonEmptyText,
    ShortText,
    Token,
    keyed_by,
    unique_items,
)
from dynamisbench.domain.spec.benchmark import (
    CREDIBILITY_LADDER,
    BenchmarkRelease,
    CredibilityLevel,
)
from dynamisbench.domain.spec.capability import (
    Capability,
    CapabilityDeclaration,
    CapabilityRequirement,
    EngineBinding,
)
from dynamisbench.domain.spec.environment import (
    ComponentKind,
    EnvironmentDefinition,
    EnvironmentRequirement,
)
from dynamisbench.domain.spec.identifiers import (
    BenchmarkId,
    BenchmarkRef,
    Comparator,
    EnvironmentId,
    EnvironmentRef,
    FactorId,
    Identifier,
    MetricId,
    MetricRef,
    Name,
    QuantityId,
    QuantityRef,
    RealizationId,
    RealizationRef,
    ReferenceId,
    ReferenceRef,
    ScenarioId,
    ScenarioRef,
    Sha256Hex,
    StudyId,
    StudyRef,
    SUTId,
    SUTRef,
    Version,
    VersionClause,
    VersionedRef,
    VersionSpecifier,
    WorkspaceRelativePath,
)
from dynamisbench.domain.spec.metrics import (
    AggregationMethod,
    ComparisonOperator,
    MetricAggregation,
    MetricCriterion,
    MetricDefinition,
)
from dynamisbench.domain.spec.quantities import (
    AxisConvention,
    BodyInclusion,
    CanonicalUnit,
    CompositeAggregation,
    Handedness,
    PhysicalDimension,
    QuantityDefinition,
    ReferenceFrame,
    RotationSense,
    SamplingKind,
    SamplingSemantics,
    SignConvention,
    TimeBasis,
    TimeBasisKind,
    UncertaintyMetadata,
)
from dynamisbench.domain.spec.realizations import (
    AssetReference,
    ConfigurationEntry,
    NormalizationTransform,
    RealizationDefinition,
    RealizationQuantityMapping,
)
from dynamisbench.domain.spec.references import (
    ReferenceDefinition,
    ReferenceOrigin,
    VerificationCategory,
)
from dynamisbench.domain.spec.scenarios import (
    EventDefinition,
    QuantityAssignment,
    ScenarioDefinition,
)
from dynamisbench.domain.spec.sut import (
    SUTDefinition,
    SUTInterface,
    SUTInterfaceKind,
    SUTKind,
    SUTProvenance,
)

__all__ = [
    "CREDIBILITY_LADDER",
    "AggregationMethod",
    "AssetReference",
    "AxisConvention",
    "BenchmarkId",
    "BenchmarkRef",
    "BenchmarkRelease",
    "BodyInclusion",
    "CanonicalUnit",
    "Capability",
    "CapabilityDeclaration",
    "CapabilityRequirement",
    "Comparator",
    "ComparisonOperator",
    "CompositeAggregation",
    "ComponentKind",
    "ConfigurationEntry",
    "CredibilityLevel",
    "DomainModel",
    "EngineBinding",
    "EnvironmentDefinition",
    "EnvironmentId",
    "EnvironmentRef",
    "EnvironmentRequirement",
    "EventDefinition",
    "FactorId",
    "Handedness",
    "Identifier",
    "MetricAggregation",
    "MetricCriterion",
    "MetricDefinition",
    "MetricId",
    "MetricRef",
    "Name",
    "NonEmptyText",
    "NormalizationTransform",
    "PhysicalDimension",
    "QuantityAssignment",
    "QuantityDefinition",
    "QuantityId",
    "QuantityRef",
    "RealizationDefinition",
    "RealizationId",
    "RealizationQuantityMapping",
    "RealizationRef",
    "ReferenceDefinition",
    "ReferenceFrame",
    "ReferenceId",
    "ReferenceOrigin",
    "ReferenceRef",
    "RotationSense",
    "SUTDefinition",
    "SUTId",
    "SUTInterface",
    "SUTInterfaceKind",
    "SUTKind",
    "SUTProvenance",
    "SUTRef",
    "SamplingKind",
    "SamplingSemantics",
    "ScenarioDefinition",
    "ScenarioId",
    "ScenarioRef",
    "Sha256Hex",
    "ShortText",
    "SignConvention",
    "StudyId",
    "StudyRef",
    "TimeBasis",
    "TimeBasisKind",
    "Token",
    "UncertaintyMetadata",
    "VerificationCategory",
    "Version",
    "VersionClause",
    "VersionedRef",
    "VersionSpecifier",
    "WorkspaceRelativePath",
    "keyed_by",
    "unique_items",
]
